[package]
name = "libfmod"
version = "0.1.4"
edition = "2021"
license-file = "LICENSE"
description = "A library wrapper for integrating FMOD Engine in Rust applications."
readme = "README.md"
homepage = "https://github.com/lebedev-games/libfmod"
repository = "https://github.com/lebedev-games/libfmod"

[dependencies]
